### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by andreaslarssen** [halloverden/symfony-oidc-client-bundle#2]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 222:
!!                                                                                 
!!    The child config "default_client_configuration" under "hallo_verden_oidc_client" must be configured.                                                    
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by truszko1** [comment]
You need to copy `Resources/config/hallo_verden_oidc_client.yaml` into your project's `config/packages` directory and then install the package.

**Comment by tomme87** [comment]
Fixed with #3
